/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.github.electronstudio.jaylib.ffm)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24) // or higher
    }
}
tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "com.karel.Main" // Replace with your main class
        )
    }
}

group = "com.karel"
version = "1.0-SNAPSHOT"
description = "karelsurvival"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
